STINBank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bank.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bank/urls.py
from django.shortcuts import redirect
from django.urls import path

from STINBank.utils.config import get_project_config
from bank.views import DashboardView, AccountDetailView, AccountTransactionHistoryView, AccountTransactionView, \
    ChangeDefaultCurrencyBalance, AddFundsView, SubtractFundsView

app_name = 'bank'

urlpatterns = [
    path('', lambda request: redirect(get_project_config().default_page, permanent=True)),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('account/<int:pk>/', AccountDetailView.as_view(), name='account-detail'),
    path('account/<int:pk>/history', AccountTransactionHistoryView.as_view(), name='account-history'),
    path('account/<int:pk>/transaction', AccountTransactionView.as_view(), name='account-transaction'),
    path(
        'account/<int:pk>/change-default-currency',
        ChangeDefaultCurrencyBalance.as_view(),
        name='account-change-default-currency'
    ),
    path('account/<int:pk>/add-funds', AddFundsView.as_view(), name='account-add-funds'),
    path('account/<int:pk>/subtract-funds', SubtractFundsView.as_view(), name='account-subtract-funds'),
]

bank/forms.py
from django import forms

from bank.models import Account
from bank.utils.currency import CURRENCIES__MODELS, CURRENCIES


class TransactionForm(forms.Form):
    origin_account_pk = forms.IntegerField(
        label='',
        widget=forms.HiddenInput()
    )
    target_account_number = forms.CharField(
        label='Číslo cílového účtu', max_length=24,
        widget=forms.TextInput(attrs={'class': 'input'})
    )
    currency = forms.ChoiceField(label='Měna', choices=CURRENCIES__MODELS)
    amount = forms.DecimalField(
        label='Částka', max_digits=12, decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'input'})
    )

    origin_account: Account = None
    target_account: Account = None

    def __init__(self, account: Account, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if account:
            self.fields['origin_account_pk'].initial = account.pk
            self.fields['currency'].initial = account.get_default_currency()

    def clean(self):
        cleaned_data = super().clean()

        try:
            self.origin_account = Account.objects.get(pk=cleaned_data['origin_account_pk'])
            self.target_account = Account.objects.get(account_number=cleaned_data['target_account_number'])
        except Account.DoesNotExist:
            raise forms.ValidationError('Cílový účet neexistuje.')

        return cleaned_data


class AlterFundsForm(forms.Form):
    currency = forms.ChoiceField(label='Měna', choices=CURRENCIES__MODELS)
    amount = forms.DecimalField(
        max_digits=12, decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'input', 'placeholder': 'Částka'})
    )

bank/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpRequest
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, DetailView, ListView, FormView

from STINBank.utils.config import get_bank_config
from STINBank.utils.permissions import require_account_owner
from STINBank.utils.template import push_form_errors_to_messages
from STINBank.views import BankView
from bank.forms import TransactionForm, AlterFundsForm
from bank.models import Account, Transaction, AccountBalance


# Create your views here.

class DashboardView(BankView, TemplateView):
    template_name = 'dashboard.html'
    title = 'Dashboard'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['accounts'] = Account.objects.for_user(self.request.user)

        return context


class AccountDetailView(BankView, DetailView):
    template_name = 'account_detail.html'
    model = Account

    def test_func(self, request: HttpRequest, *args, **kwargs):
        return self.get_object().owner == request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['alter_funds_form'] = AlterFundsForm()

        return context

    def get_title(self):
        return self.object.display_name


class AccountTransactionHistoryView(BankView, ListView):
    template_name = 'transaction_history.html'
    model = Transaction
    title = 'Historie transakcí'
    paginate_by = get_bank_config().transaction_history_paginate_by

    account: Account = None

    def test_func(self, request: HttpRequest, *args, **kwargs):
        return require_account_owner(kwargs['pk'], request.user)

    def get(self, request, *args, **kwargs):
        self.account = Account.objects.get(pk=kwargs['pk'])
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['account'] = self.account

        return context

    def get_queryset(self):
        return self.account.get_transactions().order_by('-created_at')


class AccountTransactionView(BankView, FormView):
    template_name = 'transaction.html'
    form_class = TransactionForm
    title = 'Transakce'
    success_url = reverse_lazy('bank:dashboard')
    account: Account = None

    def test_func(self, request: HttpRequest, *args, **kwargs):
        return require_account_owner(kwargs['pk'], request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['account'] = self.account
        return kwargs

    def get(self, request, *args, **kwargs):
        self.account = Account.objects.get(pk=self.kwargs['pk'])
        return super().get(request, *args, **kwargs)

    def form_invalid(self, form):
        push_form_errors_to_messages(self.request, form)
        return super().form_invalid(form)

    def form_valid(self, form):
        transaction = Transaction(
            origin=form.origin_account,
            target=form.target_account,
            currency=form.cleaned_data['currency'],
            amount=float(form.cleaned_data['amount'])
        )
        try:
            transaction.authorize()
            messages.success(self.request, 'Transakce byla úspěšně provedena.')
        except Transaction.InsufficientFunds as e:
            messages.error(self.request, str(e))
        return super().form_valid(form)


class ChangeDefaultCurrencyBalance(BankView, View):
    def test_func(self, request: HttpRequest, *args, **kwargs):
        return require_account_owner(kwargs['pk'], request.user)

    def post(self, request, *args, **kwargs):
        account: Account = Account.objects.get(pk=self.kwargs['pk'])
        current_default_balance: AccountBalance = account.get_default_balance()
        new_default_balance: AccountBalance = account.get_balance(request.POST['currency'])
        new_default_balance.set_default()
        messages.success(
            request,
            f'Výchozí měna účtu byla změněna z {current_default_balance.currency} na {new_default_balance.currency}.'
        )
        return HttpResponseRedirect(reverse('bank:account-detail', kwargs={'pk': account.pk}))


class AddFundsView(BankView, View):
    def test_func(self, request: HttpRequest, *args, **kwargs):
        return require_account_owner(kwargs['pk'], request.user)

    def post(self, request, *args, **kwargs):
        account: Account = Account.objects.get(pk=self.kwargs['pk'])
        Transaction.objects.create_non_transfer(
            account, Transaction.TransactionType.DEPOSIT,
            float(request.POST['amount']), request.POST['currency'],
            request
        )
        return HttpResponseRedirect(reverse('bank:account-detail', kwargs={'pk': account.pk}))


class SubtractFundsView(BankView, View):
    def test_func(self, request: HttpRequest, *args, **kwargs):
        return require_account_owner(kwargs['pk'], request.user)

    def post(self, request, *args, **kwargs):
        account: Account = Account.objects.get(pk=self.kwargs['pk'])
        currency_balance: AccountBalance = account.get_balance(request.POST['currency'])
        if currency_balance.balance == 0:
            currency_balance.delete()
            messages.success(request, f'Měnový účet {request.POST["currency"]} byl smazán.')
        else:
            Transaction.objects.create_non_transfer(
                account, Transaction.TransactionType.WITHDRAWAL,
                float(request.POST['amount']), request.POST['currency'],
                request
            )
        return HttpResponseRedirect(reverse('bank:account-detail', kwargs={'pk': account.pk}))

bank/templates/includes/account_balance_card.html
<div class="column is-4">
    <div class="card">
        <header class="card-header is-flex is-justify-content-space-between">
            <p class="px-3 py-4 has-text-weight-medium">
                {{ balance.balance_display }}
                <span class="has-text-weight-light">({{ balance.currency }})</span>
            </p>
            <section class="is-flex">
                {% if balance.balance != 0 or not balance.default_balance %}
                    <form method="post" action="{% if balance.balance > 0 %}{% url 'bank:account-subtract-funds' account.pk %}{% else %}{% url 'bank:account-add-funds' account.pk %}{% endif %}" class="pr-2">
                    {% csrf_token %}
                    <input type="hidden" name="currency" value="{{ balance.currency }}">
                    <input type="hidden" name="amount" value="{{ balance.balance }}">
                    <a title="Vynulovat měnový účet" onclick="this.parentElement.submit()">
                        <i class="fa-solid fa-xmark has-text-danger"></i>
                    </a>
                {% endif %}
                </form>
                {% if balance.default_balance %}
                    <span class="tag is-success is-light" style="border-radius: 0 4px 0 4px">Default</span>
                {% else %}
                    <form action="{% url 'bank:account-change-default-currency' balance.account.pk %}"
                          method="post">
                        {% csrf_token %}
                        <input type="hidden" name="currency" value="{{ balance.currency }}">
                        <input type="checkbox" onclick="this.form.submit()" class="m-2"
                               title="Nastavit tuto měnu jako výchozí pro tento účet">
                    </form>
                {% endif %}
            </section>
        </header>
    </div>
</div>

bank/templates/includes/account_card.html
{% load bank_template %}
<div class="card">
    <a href="{% url 'bank:account-detail' account.pk %}">
        <header class="card-header p-1">
            <div class="p-4">
                <i class="fa-solid fa-coins"></i>
            </div>
            <div class="my-auto">
                <p class="has-text-weight-bold has-text-info-dark">
                    {{ account.display_name }}
                </p>
                <p class="has-text-grey">{{ account.get_account_number }}</p>
            </div>
        </header>
    </a>
    <div class="card-content p-3">
        <div class="content has-text-right" style="padding-top: 75px;">
            <p class="has-text-grey m-0">aktuální použitelný zůstatek</p>
            {% render_account_balance account request 5 %}
        </div>
        <div class="is-flex is-justify-content-space-around">
            <a href="{% url 'bank:account-transaction' account.pk %}" class="button is-danger px-5">Platba</a>
            <a href="{% url 'bank:account-history' account.pk %}" class="button is-danger px-5">Historie</a>
        </div>
    </div>
</div>

bank/templates/includes/monetary_value.html
<span class="is-size-{{ size }} has-text-weight-bold">
    {{ whole_part }},<span class="is-size-{{ size|add:1 }}">{{ decimal_part }}</span>
</span>

bank/templates/includes/transaction_history_table.html
{% extends 'includes/base_table.html' %}
{% load bank_template %}
{% block table_class %}
    is-fullwidth is-hoverable is-striped mb-3
{% endblock %}
{% block head %}
    <th>Datum</th>
    <th></th>
    <th>Popis</th>
    <th>Částka</th>
{% endblock %}
{% block for_each_row %}
    {% render_transaction_table_row row account request %}
{% endblock %}
{% block empty_message %}
    No transactions have been made from or to this account.
{% endblock %}l %}

bank/templates/includes/transaction_table_row.html
{% load bank_template %}
<tr>
    <td>
        <p>{{ transaction.created_at|date:'d.n.' }}</p>
        <p class="is-size-7 has-text-grey">
            {{ transaction.created_at.year }}
        </p>
    </td>
    <td>
        {% if transaction.type == 'TRANSFER' %}
            {% if is_incoming_transfer %}
                <i class="fa-solid fa-share has-text-success"></i>
            {% elif is_outgoing_transfer %}
                <i class="fa-solid fa-reply has-text-danger"></i>
            {% else %}
                <i class="fa-solid fa-question"></i>
            {% endif %}
        {% elif transaction.type == 'DEPOSIT' %}
            <i class="fa-solid fa-money-bill-transfer has-text-success"></i>
        {% elif transaction.type == 'WITHDRAWAL' %}
            <i class="fa-solid fa-money-bill-transfer has-text-danger"></i>
        {% endif %}
    </td>
    <td>
        <p class="is-size-6">
            {% if transaction.type == 'TRANSFER' %}
                {% if is_incoming_transfer %}
                    {{ transaction.origin.display_name }}
                {% elif is_outgoing_transfer %}
                    {{ transaction.target.display_name }}
                {% else %}

                {% endif %}
            {% elif transaction.type == 'DEPOSIT' %}
                Vklad na účet
            {% elif transaction.type == 'WITHDRAWAL' %}
                Výběr z bankomatu
            {% endif %}
        </p>
        <p class="is-size-7 has-text-grey">
            <span>
                {% if transaction.type == 'TRANSFER' %}
                    {% if is_incoming_transfer %}
                        Příchozí úhrada: {{ transaction.origin.get_account_number }}
                    {% elif is_outgoing_transfer %}
                        Odchozí úhrada: {{ transaction.target.get_account_number }}
                    {% endif %}
                {% endif %}
            </span>
        </p>
    </td>
    <td>
        <p class="{% if transaction_direction < 0 %}has-text-danger-dark{% elif transaction_direction > 0 %}has-text-success-dark{% endif %}">
            {% render_monetary_value transaction.amount transaction.currency 6 %}
        </p>
    </td>
</tr>