STINBank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bank.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path

from accounts.views import BankLogoutView, BankLoginView, PreferencesView, BankPasswordChangeView, BankVerifyTOTPView

app_name = 'accounts'

urlpatterns = [
    path("login/", BankLoginView.as_view(

    ), name="login"),
    path('login/verify', BankVerifyTOTPView.as_view(), name='login-totp-verify'),
    path("logout/", BankLogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        BankPasswordChangeView.as_view(),
        name="password_change"
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path('preferences/', PreferencesView.as_view(), name='preferences')
]

bank/urls.py
from django.shortcuts import redirect
from django.urls import path

from STINBank.utils.config import get_project_config
from bank.views import DashboardView, AccountDetailView, AccountTransactionHistoryView, AccountTransactionView, \
    ChangeDefaultCurrencyBalance, AddFundsView, SubtractFundsView

app_name = 'bank'

urlpatterns = [
    path('', lambda request: redirect(get_project_config().default_page, permanent=True)),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('account/<int:pk>/', AccountDetailView.as_view(), name='account-detail'),
    path('account/<int:pk>/history', AccountTransactionHistoryView.as_view(), name='account-history'),
    path('account/<int:pk>/transaction', AccountTransactionView.as_view(), name='account-transaction'),
    path(
        'account/<int:pk>/change-default-currency',
        ChangeDefaultCurrencyBalance.as_view(),
        name='account-change-default-currency'
    ),
    path('account/<int:pk>/add-funds', AddFundsView.as_view(), name='account-add-funds'),
    path('account/<int:pk>/subtract-funds', SubtractFundsView.as_view(), name='account-subtract-funds'),
]

STINBank/views.py
from django.contrib import messages
from django.contrib.auth.mixins import AccessMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect

from STINBank.utils.config import get_project_config


class BankView(AccessMixin):
    title: str = None
    login_required: bool = True

    def test_func(self, request: HttpRequest, *args, **kwargs):
        """
        Yoinked from the Django built-in UserPassesTestMixin
        """
        pass

    def handle_test_fail(self, request) -> HttpResponse:
        messages.error(request, 'Nemáte oprávnění k přístupu na tuto stránku.')
        try:
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        except KeyError:
            return HttpResponseRedirect(get_project_config().default_page)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = self.get_title()

        return context

    def dispatch(self, request, *args, **kwargs):
        test_func = self.test_func(request, *args, **kwargs)
        if test_func is not None and not test_func:
            return self.handle_test_fail(request)
        if not request.user.is_authenticated and self.login_required:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def get_title(self):
        return self.title

STINBank/templates/includes/base_table.html
{% if rows %}
    <table class="table {% block table_class %}mb-1 is-fullwidth is-hoverable{% endblock %}">
        <thead>
        <tr>{% block head %}{% endblock %}</tr>
        </thead>
        <tbody>
        {% for row in rows %}
            {% block for_each_row %}{% endblock %}
        {% endfor %}
        </tbody>
    </table>
    {% if paginator %}
        {% include 'includes/pagination/pagination.html' with paginator=paginator page_obj=page_obj %}
    {% endif %}
    {% if limit %}
        <section>
            <p class="has-text-grey-light mb-2">Showing {{ limit }} results</p>
            <div class="buttons is-justify-content-center">
                <a href="?{{ limit_query_parameter }}={{ limit|add:base_limit }}#{{ limit_button_id }}"
                   class="button"
                   id="{{ limit_button_id }}">
                    Show more
                </a>
                <a onclick="clearPaginationUrl('{{ limit_query_parameter }}')" class="button">Reset</a>
            </div>
        </section>
    {% endif %}
{% else %}
    <span class="has-text-grey-light">
        {% block empty_message %}
            No records found.
        {% endblock %}
    </span>
{% endif %}

STINBank/templates/includes/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link href="{% static 'css/bulma-switch.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bulma-pageloader.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet">

STINBank/templates/includes/footer.html
<footer>
    <div class="container mt-4">
        <div class="columns">
            <div class="column is-6 has-text-left has-text-centered-mobile">
                Copyright &copy;
                <script>document.write(new Date().getFullYear().toString())</script>
                <a href="https://github.com/Pzdrs">Petr Boháč</a>
            </div>
            <div class="column is-6 has-text-right is-hidden-mobile">
                <i class="fa-solid fa-envelope px-1"></i>
                <a href="mailto:mojebanka@stb.cz">mojebanka@stb.cz</a>
                <i class="fa-solid fa-phone pl-3 pr-1"></i>
                <span>+420 955 551 552</span>
            </div>
        </div>
    </div>
</footer>

STINBank/templates/includes/form.html
{% load common_template %}
{% for field in form %}
    {% if field_wrap %}
        <div class="field">
            {{ field.errors }}
            {% if label %}
                <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
            {% endif %}
            <div class="control">
                {% render_form_field field %}
            </div>
            <p class="help">{{ field.help_text }}</p>
        </div>
    {% else %}
        {{ field.errors }}
        {% if label %}
            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
        {% endif %}
        <div class="control">
            {% render_form_field field %}
        </div>
        <p class="help">{{ field.help_text }}</p>
    {% endif %}
{% endfor %}

STINBank/templates/includes/header.html
<header class="top-navbar">
    <div class="container navbar pr-3" style="height: 100%; display: flex; align-items: center; justify-content: flex-end">
        <a href="{% url 'bank:dashboard' %}" class="mr-5">
            <i class="fa-solid fa-house fa-xl"></i>
        </a>
        <a class="navbar-item is-hidden-mobile" style="pointer-events: none">
            <i class="fa-solid fa-envelope"></i>
            Zprávy
        </a>
        <a class="navbar-item is-hidden-mobile" style="pointer-events: none">
            <i class="fa-solid fa-user"></i>
            {{ request.user.get_full_name }}
        </a>
        <a href="{% url 'accounts:preferences' %}" class="navbar-item" onclick="anchorPageLoad(this)">
            <i class="fa-solid fa-gear"></i>
            Nastavení
        </a>
        <a href="{% url 'accounts:logout' %}" class="logout">
            <i class="fa-solid fa-power-off fa-xl has-text-danger-dark"></i>
        </a>
    </div>
</header>

STINBank/templates/includes/js.html
{% load static %}
<script type="text/javascript" src="https://unpkg.com/bulma-modal-fx/dist/js/modal-fx.min.js" defer></script>
<script src="{% static 'js/pageloader.js' %}" defer></script>
<script src="{% static 'js/htmx.min.js' %}"></script>

STINBank/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="notification {{ message.tags }}">
            <button class="delete" onclick="this.parentElement.remove()"></button>
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}

STINBank/templates/includes/page_loader.html
<div id="pageloader" class="pageloader">
    <span id="pageloader-title" class="title">Loading...</span>
</div>