STINBank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bank.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path

from accounts.views import BankLogoutView, BankLoginView, PreferencesView, BankPasswordChangeView, BankVerifyTOTPView

app_name = 'accounts'

urlpatterns = [
    path("login/", BankLoginView.as_view(

    ), name="login"),
    path('login/verify', BankVerifyTOTPView.as_view(), name='login-totp-verify'),
    path("logout/", BankLogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        BankPasswordChangeView.as_view(),
        name="password_change"
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path('preferences/', PreferencesView.as_view(), name='preferences')
]

bank/urls.py
from django.shortcuts import redirect
from django.urls import path

from STINBank.utils.config import get_project_config
from bank.views import DashboardView, AccountDetailView, AccountTransactionHistoryView, AccountTransactionView, \
    ChangeDefaultCurrencyBalance, AddFundsView, SubtractFundsView

app_name = 'bank'

urlpatterns = [
    path('', lambda request: redirect(get_project_config().default_page, permanent=True)),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('account/<int:pk>/', AccountDetailView.as_view(), name='account-detail'),
    path('account/<int:pk>/history', AccountTransactionHistoryView.as_view(), name='account-history'),
    path('account/<int:pk>/transaction', AccountTransactionView.as_view(), name='account-transaction'),
    path(
        'account/<int:pk>/change-default-currency',
        ChangeDefaultCurrencyBalance.as_view(),
        name='account-change-default-currency'
    ),
    path('account/<int:pk>/add-funds', AddFundsView.as_view(), name='account-add-funds'),
    path('account/<int:pk>/subtract-funds', SubtractFundsView.as_view(), name='account-subtract-funds'),
]

accounts/models.py
import os

import pyotp
from decouple import config
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from STINBank.utils.config import get_bank_config
from bank.utils.currency import CURRENCIES__MODELS, get_currency_display


class User(AbstractUser):
    preferred_currency = models.CharField(max_length=3, choices=CURRENCIES__MODELS, null=True, blank=True)
    use_2fa = models.BooleanField(default=False)
    pending_verification = models.BooleanField(default=False)

    def delete(self, using=None, keep_parents=False):
        # check if they have a qrcode generated and delete it
        path = os.path.join(settings.MEDIA_ROOT, 'qr_codes', f'{self.pk}.png')
        if os.path.exists(path):
            os.remove(path)
        return super().delete(using, keep_parents)

    def get_preferred_currency_display(self):
        return get_currency_display(self.preferred_currency)

    def has_preferred_currency(self):
        return self.preferred_currency is not None

    def get_full_name_reversed(self):
        return f'{self.last_name} {self.first_name}'.strip()

    def has_pending_verification(self):
        return self.pending_verification

    def is_using_2fa(self):
        return self.use_2fa

    def set_pending_verification(self, state: bool):
        self.pending_verification = state
        self.save()

    def get_totp_uri(self):
        return pyotp.totp.TOTP(config('TOTP_KEY')).provisioning_uri(
            name=self.username,
            issuer_name=get_bank_config().name
        )

accounts/forms.py
from django.forms import ModelForm

from accounts.models import User


class UserForm(ModelForm):
    def __init__(self, data=None, instance=None):
        super().__init__(data, instance=instance)
        for field in self.fields:
            self.fields[field].required = False

    class Meta:
        model = User
        fields = '__all__'


class PreferredCurrencyForm(ModelForm):
    class Meta:
        model = User
        fields = ('preferred_currency',)

accounts/views.py
import pyotp
from amqp import ConnectionForced
from celery.app.control import Inspect
from decouple import config
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView
from kombu.exceptions import OperationalError

from STINBank.celery import app
from STINBank.utils.config import get_project_config
from STINBank.views import BankView
from accounts.forms import PreferredCurrencyForm, UserForm
from accounts.models import User
from accounts.tasks import generate_qr_code


# Create your views here.

class BankLoginView(BankView, LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True
    login_required = False
    title = 'Přihlašte se'

    def get_success_url(self):
        user: User = self.request.user
        return reverse('accounts:login-totp-verify') if user.is_using_2fa() else reverse('bank:dashboard')

    def form_valid(self, form):
        response = super().form_valid(form)
        user: User = self.request.user
        if user.is_using_2fa():
            user.set_pending_verification(True)
        return response


class BankVerifyTOTPView(BankView, TemplateView):
    template_name = 'verify_totp.html'
    title = 'Ověření uživatele'

    def get(self, request, *args, **kwargs):
        using_2fa = request.user.is_using_2fa()
        if not using_2fa or (using_2fa and not request.user.has_pending_verification()):
            try:
                return HttpResponseRedirect(request.META['HTTP_REFERER'])
            except KeyError:
                return HttpResponseRedirect(get_project_config().default_page)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        totp = pyotp.TOTP(config('TOTP_KEY'))
        if not ('code' in request.POST.keys() and totp.verify(request.POST['code'])):
            return super().get(request, *args, **kwargs)
        request.user.set_pending_verification(False)
        return redirect(get_project_config().default_page)


class BankLogoutView(BankView, LogoutView):
    template_name = 'logout.html'
    title = 'Odhlášen'


class PreferencesView(BankView, TemplateView):
    template_name = 'preferences.html'
    title = 'Nastavení'

    def get(self, request, *args, **kwargs):
        try:
            celery_inspect: Inspect = app.control.inspect()
            if celery_inspect.active() is None:
                messages.warning(request, 'Celery worker není spuštěný, není možné vygenerovat 2FA QR kód.')
            else:
                generate_qr_code.delay(request.user.pk)
        except Exception:
            messages.warning(
                request,
                'Služba RabbitMQ pravděpodobně není k dispozici, není možné vygenerovat 2FA QR kód.'
            )
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user: User = self.request.user
        context = super().get_context_data(**kwargs)
        context['2fa'] = user.is_using_2fa()
        context['fallback_totp_uri'] = user.get_totp_uri()
        context['preferred_currency_form'] = PreferredCurrencyForm(initial={
            'preferred_currency': user.preferred_currency
        })
        return context

    def post(self, request, *args, **kwargs):
        user_form = UserForm(data=request.POST, instance=request.user)
        instance = user_form.save(commit=False)
        instance.save(update_fields=tuple(request.POST.keys())[1:])
        return redirect(reverse('accounts:preferences'))


class BankPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('accounts:preferences')

    def form_valid(self, form):
        messages.success(self.request, 'Heslo úspěšně změněno.')
        return super().form_valid(form)

accounts/templates/login.html
{% extends 'base_template.html' %}
{% block body %}
    <div class="hero is-fullheight" style="background-color: #efefef">
        <div class="hero-body is-justify-content-center is-align-items-center">
            <form method="post">{% csrf_token %}
                <div class="columns is-flex is-flex-direction-column box">
                    <div class="column">
                        <label class="label" for="username">Username</label>
                        <input name="username" class="input is-info" type="text" placeholder="Username">
                    </div>
                    <div class="column">
                        <label class="label" for="password">Password</label>
                        <input name="password" class="input is-info" type="password" placeholder="Password">
                        <a href="#" class="is-size-7 has-text-grey">Forgot password?</a>
                    </div>
                    <div class="column">
                        <button class="button is-link is-fullwidth" type="submit">
                            <i class="fa-solid fa-right-to-bracket"></i>&nbsp;
                            Sign in
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/logout.html
{% extends 'base_template.html' %}
{% block body %}
    <section class="hero is-light is-fullheight">
        <div class="hero-body">
            <div class="container">
                <div class="columns is-centered">
                    <div class="column is-two-thirds has-text-centered">
                        <h1 class="title is-1">
                            Byl/a jste odhlášen/a
                        </h1>
                        <p class="subtitle is-3">
                            Můžete se znovu přihlásit níže.
                        </p>
                        <a class="button is-large is-link" href="{% url 'accounts:login' %}">
                            Přihlásit se
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/preferences.html
{% extends 'base_template.html' %}
{% load common_template %}
{% load static %}
{% block extra_js %}
    {{ 2fa|json_script:'twoFA_status' }}
    <script src="{% static 'js/preferences.js' %}" defer></script>
{% endblock %}
{% block content %}
    <p class="is-size-4 has-text-info-dark">
        Zobrazení
    </p>
    <hr class="my-2">
    <p class="is-size-5 has-text-info">Preferovaná měna</p>
    {% if request.user.has_preferred_currency %}
        <p class="has-text-grey">Vaše preferovaná měna je <span
                class="has-text-weight-bold">{{ request.user.get_preferred_currency_display }}</span></p>
    {% else %}
        <p class="has-text-grey">Nemáte nastavenou preferovano měnu</p>
    {% endif %}
    <form method="post" class="mt-2">{% csrf_token %}
        <div class="field has-addons">
            {% render_form preferred_currency_form False False %}
            <div class="control">
                <input type="submit" class="button is-primary" value="Změnit měnu">
            </div>
            <div class="control">
                <input type="button" class="button is-danger" value="Zrušit preferenci"
                       onclick="document.getElementById('id_preferred_currency').value='';this.form.submit()">
            </div>
        </div>
    </form>
    <p class="is-size-4 has-text-info-dark mt-5">
        Soukromí
    </p>
    <hr class="my-2">
    <p class="is-size-5 has-text-info">Přihlášení</p>
    <div class="buttons mt-2">
        <a href="{% url 'accounts:password_change' %}" class="button is-primary">Změna hesla</a>
    </div>
    <div class="is-flex">
        <p class="is-size-5 has-text-info">Dvoufázové ověření</p>
        <div class="field ml-3">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" id="twoFAhidden" name="use_2fa">
                <input id="twoFA_switch" type="checkbox" class="switch is-outlined" onchange="form_submit(this)">
                <label for="twoFA_switch"></label>
            </form>
        </div>
        <button class="button modal-button" data-target="open-2fa-qrcode">
            <i class="fa-solid fa-qrcode mr-2"></i>
            <span>Zobrazit QR kód</span>
        </button>
    </div>
{% endblock %}
{% block modals %}
    {% include 'modals/2fa_qrcode.html' %}
{% endblock %}

accounts/templates/verify_totp.html
{% extends 'base_template.html' %}
{% load static %}
{% block extra_js %}
    <script src="{% static 'js/totp_verification.js' %}" defer></script>
{% endblock %}
{% block body %}
    <section class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-half">
                    <h1 class="title">Vložte TOTP kód</h1>
                    <form method="post">{% csrf_token %}
                        <div class="field">
                            <label class="label">Verifikační kód</label>
                            <div class="control">
                                <input class="input is-medium" type="text" name="code"
                                       placeholder="Vložte 6-místný kód" autofocus>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}